image:
  repository: docker.io/edraithenni/spazz-app
  tag: "eb191f12f531a6e07a2e200d6d532ccd2b2f112f"
replicaCount: 3
postgres:
  image: postgres:15-alpine
  database: spazzdb
  user: spazz
  password: "11111"
  storageSize: 1Gi
  storageClass: nfs-client
