image:
  repository: docker.io/edraithenni/spazz-app
  tag: "3a90919453b9ab59de0d1e3da4a69623c98f26f7"
replicaCount: 3
postgres:
  image: postgres:15-alpine
  database: spazzdb
  user: spazz
  password: "11111"
  storageSize: 1Gi
  storageClass: nfs-client
