apiVersion: apps/v1
kind: Deployment
metadata:
  name: spazz-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spazz-app
  template:
    metadata:
      labels:
        app: spazz-app
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_TYPE
              value: "postgres"
            - name: DB_PATH
              value: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}?sslmode=disable"

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
