apiVersion: batch/v1
kind: Job
metadata:
  name: "migrate-db-{{ .Release.Revision }}"
#  annotations:
#   "helm.sh/hook": pre-install,pre-upgrade
#    "helm.sh/hook-weight": "-5"
#    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: alpine:3.6
          command:
            - /bin/sh
            - -c
            - 'until nc -z postgres 5432; do sleep 1; done'
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /migrations/migrate
            - -database
            - "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}?sslmode=disable"
            - -path
            - /migrations/schemes
            - up
